version: 2
updates:
- package-ecosystem: nuget
  directory: "/src"
  labels:
    - "Type: ðŸ›‘ dependency"
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 10
  target-branch: "develop"
